// Cloudflare Worker — serve Conclick's SEO engine under conclick.io
// ---------------------------------------------------------------------------
// Visitors and Google only ever see conclick.io URLs. SEO paths are reverse-
// proxied to the Next.js app on Fly; every other path falls through to Framer.
//
// Setup (one-time, in the Cloudflare dashboard for the conclick.io zone):
//   1. SSL/TLS → Overview → set mode to "Full" (NOT Flexible — Flexible loops).
//   2. DNS → set conclick.io (and www) records to Proxied (orange cloud).
//   3. Workers & Pages → create this Worker → Settings → Triggers → add Routes:
//        conclick.io/vs/*            conclick.io/alternatives/*
//        conclick.io/tools/*         conclick.io/glossary/*
//        conclick.io/guides/*        conclick.io/for/*
//        conclick.io/blog/*          conclick.io/sitemap.xml
//        conclick.io/robots.txt
//      (The Worker only fires on these paths, so the Framer homepage, pricing,
//       etc. are untouched — they pass straight through to Framer.)
// ---------------------------------------------------------------------------

const APP_ORIGIN = 'https://app.conclick.io';

// IndexNow key. Generated by scripts/seo/indexnow.mjs and mirrored here on
// purpose — this MUST be served by the Worker, never by Next.js.
//
// Why: the Worker is a strict path allowlist (see the routes in wrangler.toml).
// A key served from a Next route would 404 until that route existed, and would
// 404 again on every Fly cold start, redeploy window, or app outage. IndexNow
// treats a key file that fails to resolve as a forged key and PERMANENTLY
// distrusts it for the host — there is no re-verification flow. An inline
// constant at the edge has no origin dependency and cannot cold-start.
//
// If you rotate the key: update scripts/seo/indexnow-key.txt, update this
// constant, add the new /<key>.txt route to wrangler.toml, and redeploy the
// Worker BEFORE the next submission.
const INDEXNOW_KEY = '67409878d24e964b1928338aac760bc0';

// ---------------------------------------------------------------------------
// !!! READ THIS BEFORE TRUSTING robots.txt !!!
//
// Cloudflare's MANAGED robots.txt feature PREPENDS its own block above whatever
// this Worker returns. If it is enabled, its rules land first and ours are, at
// best, decorative — and at worst directly contradicted (the managed block ships
// AI-crawler `Disallow` lines, which would silently un-list us from ChatGPT,
// Perplexity, and Claude retrieval while this file claims the opposite).
//
// DISABLED 2026-07-22. It had been on since the zone was set up, so every
// `Allow` below was cosmetic and GPTBot/ClaudeBot/Google-Extended were each
// carrying a `Disallow: /` above their allow line.
//
// The toggle is NOT under Security -> Bots, which is where this comment used to
// send people and where the docs' "Security Settings -> Bot traffic" wording
// also points. The switch lives at:
//   Cloudflare dashboard -> conclick.io zone
//     -> AI Crawl Control -> Signals -> "Managed robots.txt"
//
// Verify:  curl -s https://conclick.io/robots.txt | head -1
// The FIRST line must be the "# Conclick" comment below. If anything precedes
// it, the managed block is back on and this allowlist is cosmetic again.
//
// Worth re-checking after 2026-09-15: Cloudflare changes its AI-bot defaults
// that day. conclick.io currently has Search/Agent/Training all set to "Allow
// (do not block)" and "Block AI bots" off, which is what keeps mixed-purpose
// crawlers like GPTBot reachable — the new defaults bite zones that block
// Training, not this one. Confirm it stayed that way.
// ---------------------------------------------------------------------------
const ROBOTS = `# Conclick — explicit AI-crawler allowlist. See deploy/cloudflare/conclick-seo-proxy.worker.js
# Retrieval/citation crawlers are allowed by name rather than relying on the
# wildcard group: several of them do not inherit \`User-agent: *\` rules once any
# named group exists, so being explicit is the only reliable signal.

# --- OpenAI ---
User-agent: GPTBot
Allow: /

User-agent: OAI-SearchBot
Allow: /

User-agent: ChatGPT-User
Allow: /

# --- Anthropic ---
User-agent: ClaudeBot
Allow: /

User-agent: Claude-Web
Allow: /

User-agent: Claude-User
Allow: /

# --- Perplexity ---
User-agent: PerplexityBot
Allow: /

User-agent: Perplexity-User
Allow: /

# --- Google AI surfaces (AI Overviews / Gemini grounding) ---
User-agent: Google-Extended
Allow: /

# --- Everyone else ---
User-agent: *
Allow: /
Disallow: /api

# Content Signals Policy — machine-readable declaration of permitted downstream
# use. We want to be searched and cited (that is the whole point of this site);
# we do not consent to our copy being used as model training data.
Content-Signal: search=yes, ai-input=yes, ai-train=no, use=reference

Sitemap: https://conclick.io/sitemap.xml
`;

export default {
  async fetch(request) {
    const url = new URL(request.url);

    // IndexNow key verification file. Body is the bare key, nothing else — the
    // search engines fetch https://conclick.io/<key>.txt and byte-compare it to
    // the `key` field in the submission payload.
    if (url.pathname === `/${INDEXNOW_KEY}.txt`) {
      return new Response(INDEXNOW_KEY, {
        headers: {
          'content-type': 'text/plain; charset=utf-8',
          'cache-control': 'public, max-age=86400',
        },
      });
    }

    // Serve a permissive robots.txt for the public domain. The app origin keeps
    // its own `Disallow: /` so the app host is never indexed as a duplicate.
    if (url.pathname === '/robots.txt') {
      return new Response(ROBOTS, {
        headers: {
          'content-type': 'text/plain; charset=utf-8',
          'cache-control': 'public, max-age=3600',
        },
      });
    }

    // Reverse-proxy the SEO path to the Next.js app. The browser URL stays on
    // conclick.io (true rewrite, not a redirect), and the app's HTML already
    // emits conclick.io canonicals + sitemap URLs, so everything is consistent.
    const target = new URL(url.pathname + url.search, APP_ORIGIN);
    const proxied = new Request(target, request);
    proxied.headers.set('X-Forwarded-Host', url.host);
    return fetch(proxied);
  },
};
