import type { ContentEntry, ContentType } from './schema';
import { pathForType } from './schema';

// AUTO-GENERATED by scripts/seo. Do not edit by hand — re-run the pipeline.
import alternatives_fathom from './alternatives/fathom';
import alternatives_google_analytics from './alternatives/google-analytics';
import alternatives_hotjar from './alternatives/hotjar';
import alternatives_matomo from './alternatives/matomo';
import alternatives_mixpanel from './alternatives/mixpanel';
import alternatives_plausible from './alternatives/plausible';
import alternatives_posthog from './alternatives/posthog';
import alternatives_umami from './alternatives/umami';
import blog_cookie_banners_killing_your_data from './blog/cookie-banners-killing-your-data';
import blog_metrics_early_saas_should_watch from './blog/metrics-early-saas-should-watch';
import blog_vanity_metrics_are_lying from './blog/vanity-metrics-are-lying';
import blog_why_revenue_attribution_matters from './blog/why-revenue-attribution-matters';
import comparisons_clarity from './comparisons/clarity';
import comparisons_datafast from './comparisons/datafast';
import comparisons_fathom from './comparisons/fathom';
import comparisons_google_analytics from './comparisons/google-analytics';
import comparisons_hotjar from './comparisons/hotjar';
import comparisons_matomo from './comparisons/matomo';
import comparisons_mixpanel from './comparisons/mixpanel';
import comparisons_pirsch from './comparisons/pirsch';
import comparisons_plausible from './comparisons/plausible';
import comparisons_posthog from './comparisons/posthog';
import comparisons_simple_analytics from './comparisons/simple-analytics';
import comparisons_umami from './comparisons/umami';
import glossary_bounce_rate from './glossary/bounce-rate';
import glossary_conversion_funnel from './glossary/conversion-funnel';
import glossary_cookieless_analytics from './glossary/cookieless-analytics';
import glossary_first_party_cookies from './glossary/first-party-cookies';
import glossary_gdpr_compliant_analytics from './glossary/gdpr-compliant-analytics';
import glossary_heatmap from './glossary/heatmap';
import glossary_marketing_attribution from './glossary/marketing-attribution';
import glossary_revenue_attribution from './glossary/revenue-attribution';
import glossary_sessions_vs_visitors from './glossary/sessions-vs-visitors';
import glossary_utm from './glossary/utm';
import guides_do_heatmaps_need_cookie_consent from './guides/do-heatmaps-need-cookie-consent';
import guides_ga4_migration_guide from './guides/ga4-migration-guide';
import guides_gdpr_analytics_checklist from './guides/gdpr-analytics-checklist';
import guides_how_to_read_a_funnel from './guides/how-to-read-a-funnel';
import guides_is_ga4_sampling_your_data from './guides/is-ga4-sampling-your-data';
import tools_utm_builder from './tools/utm-builder';
import usecases_agencies from './use-cases/agencies';
import usecases_ecommerce from './use-cases/ecommerce';
import usecases_indie_hackers from './use-cases/indie-hackers';
import usecases_newsletters from './use-cases/newsletters';
import usecases_saas from './use-cases/saas';

const ENTRIES: ContentEntry[] = [
  alternatives_fathom,
  alternatives_google_analytics,
  alternatives_hotjar,
  alternatives_matomo,
  alternatives_mixpanel,
  alternatives_plausible,
  alternatives_posthog,
  alternatives_umami,
  blog_cookie_banners_killing_your_data,
  blog_metrics_early_saas_should_watch,
  blog_vanity_metrics_are_lying,
  blog_why_revenue_attribution_matters,
  comparisons_clarity,
  comparisons_datafast,
  comparisons_fathom,
  comparisons_google_analytics,
  comparisons_hotjar,
  comparisons_matomo,
  comparisons_mixpanel,
  comparisons_pirsch,
  comparisons_plausible,
  comparisons_posthog,
  comparisons_simple_analytics,
  comparisons_umami,
  glossary_bounce_rate,
  glossary_conversion_funnel,
  glossary_cookieless_analytics,
  glossary_first_party_cookies,
  glossary_gdpr_compliant_analytics,
  glossary_heatmap,
  glossary_marketing_attribution,
  glossary_revenue_attribution,
  glossary_sessions_vs_visitors,
  glossary_utm,
  guides_do_heatmaps_need_cookie_consent,
  guides_ga4_migration_guide,
  guides_gdpr_analytics_checklist,
  guides_how_to_read_a_funnel,
  guides_is_ga4_sampling_your_data,
  tools_utm_builder,
  usecases_agencies,
  usecases_ecommerce,
  usecases_indie_hackers,
  usecases_newsletters,
  usecases_saas,
];

export function allEntries(): ContentEntry[] {
  return ENTRIES;
}

export function entriesByType(type: ContentType): ContentEntry[] {
  return ENTRIES.filter(e => e.type === type);
}

export function getEntry(type: ContentType, slug: string): ContentEntry | undefined {
  return ENTRIES.find(e => e.type === type && e.slug === slug);
}

export function pathFor(e: ContentEntry): string {
  return pathForType(e.type, e.slug);
}

export const comparisonParams = () => entriesByType('comparison').map(e => ({ competitor: e.slug }));
export const alternativeParams = () => entriesByType('alternative').map(e => ({ competitor: e.slug }));
export const toolParams = () => entriesByType('tool').map(e => ({ tool: e.slug }));
export const glossaryParams = () => entriesByType('glossary').map(e => ({ term: e.slug }));
export const useCaseParams = () => entriesByType('useCase').map(e => ({ useCase: e.slug }));
export const guideParams = () => entriesByType('guide').map(e => ({ slug: e.slug }));
export const blogParams = () => entriesByType('blog').map(e => ({ slug: e.slug }));
