import type { ContentEntry, ContentType } from './schema';
import { pathForType } from './schema';

// AUTO-GENERATED by scripts/seo. Do not edit by hand — re-run the pipeline.
import alternatives_best_heatmap_tool_for_analytics from './alternatives/best-heatmap-tool-for-analytics';
import alternatives_fathom from './alternatives/fathom';
import alternatives_fullstory from './alternatives/fullstory';
import alternatives_google_analytics from './alternatives/google-analytics';
import alternatives_hotjar from './alternatives/hotjar';
import alternatives_matomo from './alternatives/matomo';
import alternatives_mixpanel from './alternatives/mixpanel';
import alternatives_plausible from './alternatives/plausible';
import alternatives_posthog from './alternatives/posthog';
import alternatives_umami from './alternatives/umami';
import blog_ab_testing_with_low_traffic from './blog/ab-testing-with-low-traffic';
import blog_analytics_a_pre_revenue_startup_needs from './blog/analytics-a-pre-revenue-startup-needs';
import blog_analytics_stack_for_bootstrappers from './blog/analytics-stack-for-bootstrappers';
import blog_attribution_is_guessing from './blog/attribution-is-guessing';
import blog_click_map_vs_funnel from './blog/click-map-vs-funnel';
import blog_cookie_banners_killing_your_data from './blog/cookie-banners-killing-your-data';
import blog_gave_up_on_ga4 from './blog/gave-up-on-ga4';
import blog_metrics_early_saas_should_watch from './blog/metrics-early-saas-should-watch';
import blog_per_event_pricing_trap from './blog/per-event-pricing-trap';
import blog_switching_analytics_gotchas from './blog/switching-analytics-gotchas';
import blog_vanity_metrics_are_lying from './blog/vanity-metrics-are-lying';
import blog_why_revenue_attribution_matters from './blog/why-revenue-attribution-matters';
import comparisons_amplitude from './comparisons/amplitude';
import comparisons_clarity from './comparisons/clarity';
import comparisons_datafast from './comparisons/datafast';
import comparisons_fathom from './comparisons/fathom';
import comparisons_google_analytics from './comparisons/google-analytics';
import comparisons_hotjar from './comparisons/hotjar';
import comparisons_matomo from './comparisons/matomo';
import comparisons_mixpanel from './comparisons/mixpanel';
import comparisons_pirsch from './comparisons/pirsch';
import comparisons_plausible from './comparisons/plausible';
import comparisons_posthog from './comparisons/posthog';
import comparisons_simple_analytics from './comparisons/simple-analytics';
import comparisons_umami from './comparisons/umami';
import glossary_bounce_rate from './glossary/bounce-rate';
import glossary_conversion_funnel from './glossary/conversion-funnel';
import glossary_cookieless_analytics from './glossary/cookieless-analytics';
import glossary_first_party_cookies from './glossary/first-party-cookies';
import glossary_gdpr_compliant_analytics from './glossary/gdpr-compliant-analytics';
import glossary_heatmap from './glossary/heatmap';
import glossary_marketing_attribution from './glossary/marketing-attribution';
import glossary_revenue_attribution from './glossary/revenue-attribution';
import glossary_sessions_vs_visitors from './glossary/sessions-vs-visitors';
import glossary_utm from './glossary/utm';
import glossary_what_is_llms_txt from './glossary/what-is-llms-txt';
import guides_add_analytics_to_nextjs from './guides/add-analytics-to-nextjs';
import guides_best_ai_website_analytics from './guides/best-ai-website-analytics';
import guides_conversion_funnel_software_pricing from './guides/conversion-funnel-software-pricing';
import guides_cookieless_analytics_tools from './guides/cookieless-analytics-tools';
import guides_do_heatmaps_need_cookie_consent from './guides/do-heatmaps-need-cookie-consent';
import guides_filter_bot_traffic_from_analytics from './guides/filter-bot-traffic-from-analytics';
import guides_ga4_migration_guide from './guides/ga4-migration-guide';
import guides_gdpr_analytics_checklist from './guides/gdpr-analytics-checklist';
import guides_how_to_get_cited_by_chatgpt from './guides/how-to-get-cited-by-chatgpt';
import guides_how_to_read_a_funnel from './guides/how-to-read-a-funnel';
import guides_how_to_read_a_heatmap from './guides/how-to-read-a-heatmap';
import guides_impressions_up_clicks_down from './guides/impressions-up-clicks-down';
import guides_is_ga4_sampling_your_data from './guides/is-ga4-sampling-your-data';
import guides_open_source_web_analytics_tools from './guides/open-source-web-analytics-tools';
import guides_organic_traffic_showing_as_direct from './guides/organic-traffic-showing-as-direct';
import guides_revenue_attribution_tools from './guides/revenue-attribution-tools';
import guides_should_i_block_gptbot from './guides/should-i-block-gptbot';
import guides_stripe_revenue_vs_analytics_revenue from './guides/stripe-revenue-vs-analytics-revenue';
import guides_where_users_abandon_checkout from './guides/where-users-abandon-checkout';
import guides_why_ai_traffic_shows_as_direct from './guides/why-ai-traffic-shows-as-direct';
import guides_why_is_my_page_not_indexed from './guides/why-is-my-page-not-indexed';
import tools_utm_builder from './tools/utm-builder';
import usecases_agencies from './use-cases/agencies';
import usecases_ecommerce from './use-cases/ecommerce';
import usecases_indie_hackers from './use-cases/indie-hackers';
import usecases_newsletters from './use-cases/newsletters';
import usecases_saas from './use-cases/saas';

const ENTRIES: ContentEntry[] = [
  alternatives_best_heatmap_tool_for_analytics,
  alternatives_fathom,
  alternatives_fullstory,
  alternatives_google_analytics,
  alternatives_hotjar,
  alternatives_matomo,
  alternatives_mixpanel,
  alternatives_plausible,
  alternatives_posthog,
  alternatives_umami,
  blog_ab_testing_with_low_traffic,
  blog_analytics_a_pre_revenue_startup_needs,
  blog_analytics_stack_for_bootstrappers,
  blog_attribution_is_guessing,
  blog_click_map_vs_funnel,
  blog_cookie_banners_killing_your_data,
  blog_gave_up_on_ga4,
  blog_metrics_early_saas_should_watch,
  blog_per_event_pricing_trap,
  blog_switching_analytics_gotchas,
  blog_vanity_metrics_are_lying,
  blog_why_revenue_attribution_matters,
  comparisons_amplitude,
  comparisons_clarity,
  comparisons_datafast,
  comparisons_fathom,
  comparisons_google_analytics,
  comparisons_hotjar,
  comparisons_matomo,
  comparisons_mixpanel,
  comparisons_pirsch,
  comparisons_plausible,
  comparisons_posthog,
  comparisons_simple_analytics,
  comparisons_umami,
  glossary_bounce_rate,
  glossary_conversion_funnel,
  glossary_cookieless_analytics,
  glossary_first_party_cookies,
  glossary_gdpr_compliant_analytics,
  glossary_heatmap,
  glossary_marketing_attribution,
  glossary_revenue_attribution,
  glossary_sessions_vs_visitors,
  glossary_utm,
  glossary_what_is_llms_txt,
  guides_add_analytics_to_nextjs,
  guides_best_ai_website_analytics,
  guides_conversion_funnel_software_pricing,
  guides_cookieless_analytics_tools,
  guides_do_heatmaps_need_cookie_consent,
  guides_filter_bot_traffic_from_analytics,
  guides_ga4_migration_guide,
  guides_gdpr_analytics_checklist,
  guides_how_to_get_cited_by_chatgpt,
  guides_how_to_read_a_funnel,
  guides_how_to_read_a_heatmap,
  guides_impressions_up_clicks_down,
  guides_is_ga4_sampling_your_data,
  guides_open_source_web_analytics_tools,
  guides_organic_traffic_showing_as_direct,
  guides_revenue_attribution_tools,
  guides_should_i_block_gptbot,
  guides_stripe_revenue_vs_analytics_revenue,
  guides_where_users_abandon_checkout,
  guides_why_ai_traffic_shows_as_direct,
  guides_why_is_my_page_not_indexed,
  tools_utm_builder,
  usecases_agencies,
  usecases_ecommerce,
  usecases_indie_hackers,
  usecases_newsletters,
  usecases_saas,
];

export function allEntries(): ContentEntry[] {
  return ENTRIES;
}

export function entriesByType(type: ContentType): ContentEntry[] {
  return ENTRIES.filter(e => e.type === type);
}

export function getEntry(type: ContentType, slug: string): ContentEntry | undefined {
  return ENTRIES.find(e => e.type === type && e.slug === slug);
}

export function pathFor(e: ContentEntry): string {
  return pathForType(e.type, e.slug);
}

export const comparisonParams = () => entriesByType('comparison').map(e => ({ competitor: e.slug }));
export const alternativeParams = () => entriesByType('alternative').map(e => ({ competitor: e.slug }));
export const toolParams = () => entriesByType('tool').map(e => ({ tool: e.slug }));
export const glossaryParams = () => entriesByType('glossary').map(e => ({ term: e.slug }));
export const useCaseParams = () => entriesByType('useCase').map(e => ({ useCase: e.slug }));
export const guideParams = () => entriesByType('guide').map(e => ({ slug: e.slug }));
export const blogParams = () => entriesByType('blog').map(e => ({ slug: e.slug }));
